import Link from "next/link";
import { getTranslations, getLocale } from "next-intl/server";
import { getShellContext } from "@/lib/shell-context";
import { KpiCard } from "@/components/kpi-card";
import { RealtimeRefresh } from "@/components/realtime-refresh";
import { AttendanceBoard, type BoardRow, type BoardFilters } from "@/components/attendance-board";
import { Term, SiteName } from "@/components/localized-term";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  attendanceThresholds,
  attendanceStatus,
  minutesBetween,
  summarize,
  formatMinutes,
  type AssignmentSnapshot,
} from "@/lib/attendance";

/**
 * Live operations dashboard.
 * Reads state only — attendance ALERTS are generated by the evaluation runner
 * (cron), never by rendering this page.
 */
export const dynamic = "force-dynamic";

type AssignmentRow = {
  id: string;
  employee_id: string;
  status: string;
  shifts: {
    id: string;
    start_time: string;
    end_time: string;
    required_role: string | null;
    required_count: number;
    status: string;
    jobs: { client_name: string; location_id: string | null; locations: { name: string } | null } | null;
  } | null;
  employees: {
    full_name: string;
    department_id: string | null;
    departments: { name: string } | null;
  } | null;
};

type EntryRow = {
  id: string;
  shift_assignment_id: string | null;
  clock_in: string;
  clock_out: string | null;
  clock_in_location_status: string | null;
  clock_in_distance_m: number | null;
};

export default async function DashboardPage({
  searchParams,
}: {
  searchParams: Promise<BoardFilters>;
}) {
  const ctx = await getShellContext();
  const t = await getTranslations("ops");
  const locale = await getLocale();
  const filters = await searchParams;

  const now = new Date();
  const dayStart = new Date(now);
  dayStart.setHours(0, 0, 0, 0);
  const dayEnd = new Date(dayStart);
  dayEnd.setDate(dayEnd.getDate() + 1);
  const soon = new Date(now.getTime() + 2 * 3_600_000);

  const thresholds = attendanceThresholds(ctx.company.settings);

  const [
    { data: assignments },
    { data: sites },
    { data: departments },
    { data: openShifts },
    { data: manualRequests },
    { data: alerts },
  ] = await Promise.all([
    ctx.supabase
      .from("shift_assignments")
      .select(
        "id, employee_id, status, shifts!inner(id, start_time, end_time, required_role, required_count, status, jobs(client_name, location_id, locations(name))), employees(full_name, department_id, departments(name))"
      )
      .eq("company_id", ctx.membership.company_id)
      // 'cancellation_requested' belongs on the day board: the employee is
      // still assigned and still expected until a manager approves. Dropping
      // them made someone with an open request vanish from the operational
      // view while the shift still counted as staffed.
      .in("status", ["assigned", "accepted", "cancellation_requested", "completed"])
      .gte("shifts.start_time", dayStart.toISOString())
      .lt("shifts.start_time", dayEnd.toISOString())
      .order("start_time", { referencedTable: "shifts", ascending: true }),
    ctx.supabase
      .from("locations")
      .select("id, name")
      .eq("company_id", ctx.membership.company_id)
      .order("name"),
    ctx.supabase
      .from("departments")
      .select("id, name")
      .eq("company_id", ctx.membership.company_id)
      .order("name"),
    ctx.supabase
      .from("shifts")
      .select("id, start_time, end_time, required_role, status, jobs(client_name, locations(name))")
      .eq("company_id", ctx.membership.company_id)
      .eq("status", "open")
      .gte("start_time", now.toISOString())
      .order("start_time", { ascending: true })
      .limit(8),
    ctx.supabase
      .from("manual_clockin_requests")
      .select("id")
      .eq("company_id", ctx.membership.company_id)
      .eq("status", "pending"),
    ctx.supabase
      .from("attendance_alerts")
      .select("id, type, minutes_delta, created_at, employees(full_name)")
      .eq("company_id", ctx.membership.company_id)
      .eq("status", "open")
      .gte("created_at", dayStart.toISOString())
      .order("created_at", { ascending: false })
      .limit(8),
  ]);

  const rows = (assignments ?? []) as unknown as AssignmentRow[];

  const { data: entries } = rows.length
    ? await ctx.supabase
        .from("time_entries")
        .select(
          "id, shift_assignment_id, clock_in, clock_out, clock_in_location_status, clock_in_distance_m"
        )
        .eq("company_id", ctx.membership.company_id)
        .in(
          "shift_assignment_id",
          rows.map((r) => r.id)
        )
    : { data: [] as EntryRow[] };

  const entryByAssignment = new Map<string, EntryRow>();
  for (const e of (entries ?? []) as unknown as EntryRow[]) {
    if (e.shift_assignment_id) entryByAssignment.set(e.shift_assignment_id, e);
  }

  const board: BoardRow[] = rows
    .filter((r) => r.shifts)
    .map((r) => {
      const entry = entryByAssignment.get(r.id) ?? null;
      const snapshot: AssignmentSnapshot = {
        assignmentId: r.id,
        employeeId: r.employee_id,
        assignmentStatus: r.status,
        scheduledStart: new Date(r.shifts!.start_time),
        scheduledEnd: new Date(r.shifts!.end_time),
        clockIn: entry ? new Date(entry.clock_in) : null,
        clockOut: entry?.clock_out ? new Date(entry.clock_out) : null,
        clockInLocationStatus: entry?.clock_in_location_status ?? null,
      };
      const status = attendanceStatus(snapshot, thresholds, now);
      const minutesLate = snapshot.clockIn
        ? minutesBetween(snapshot.clockIn, snapshot.scheduledStart)
        : status === "late" || status === "no_show"
          ? minutesBetween(now, snapshot.scheduledStart)
          : null;

      return {
        assignmentId: r.id,
        employeeName: r.employees?.full_name ?? "—",
        siteName: r.shifts!.jobs?.locations?.name ?? r.shifts!.jobs?.client_name ?? "—",
        departmentName: r.employees?.departments?.name ?? null,
        departmentId: r.employees?.department_id ?? null,
        locationId: r.shifts!.jobs?.location_id ?? null,
        role: r.shifts!.required_role,
        scheduledStart: snapshot.scheduledStart,
        scheduledEnd: snapshot.scheduledEnd,
        clockIn: snapshot.clockIn,
        clockOut: snapshot.clockOut,
        locationStatus: entry?.clock_in_location_status ?? null,
        distanceM: entry?.clock_in_distance_m ?? null,
        status,
        minutesLate: minutesLate != null && minutesLate > 0 ? minutesLate : null,
        cancellationPending: r.status === "cancellation_requested",
      };
    });

  const kpis = summarize(board.map((b) => b.status));
  const endingSoon = board.filter(
    (b) => b.status === "on_duty" && b.scheduledEnd > now && b.scheduledEnd <= soon
  ).length;

  const filtered = board.filter((r) => {
    if (filters.site && filters.site !== "all" && r.locationId !== filters.site) return false;
    if (filters.department && filters.department !== "all" && r.departmentId !== filters.department)
      return false;
    if (filters.status && filters.status !== "all" && r.status !== filters.status) return false;
    if (
      filters.verification &&
      filters.verification !== "all" &&
      r.locationStatus !== filters.verification
    )
      return false;
    return true;
  });

  const fmtTime = (iso: string) =>
    new Date(iso).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" });

  return (
    <div className="flex flex-col gap-5">
      <RealtimeRefresh companyId={ctx.membership.company_id} />

      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <h1 className="text-xl font-semibold tracking-tight">{t("title")}</h1>
        <p className="text-xs text-muted-foreground">
          {t("scheduledToday", { count: kpis.scheduled })} · {t("liveHint")}
        </p>
      </div>

      <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">
        <KpiCard label={t("kpiOnDuty")} value={kpis.onDuty} tone="good" href="/app?status=on_duty" />
        <KpiCard label={t("kpiLate")} value={kpis.late} tone={kpis.late ? "warn" : "neutral"} href="/app?status=late" />
        <KpiCard
          label={t("kpiNoShow")}
          value={kpis.noShow}
          tone={kpis.noShow ? "critical" : "neutral"}
          href="/app?status=no_show"
        />
        <KpiCard label={t("kpiOpenShifts")} value={(openShifts ?? []).length} tone={(openShifts ?? []).length ? "warn" : "neutral"} href="/app/shifts" />
        <KpiCard
          label={t("kpiOutside")}
          value={kpis.outsideSite}
          tone={kpis.outsideSite ? "critical" : "neutral"}
          href="/app?status=outside_geofence"
        />
        <KpiCard
          label={t("kpiManual")}
          value={(manualRequests ?? []).length}
          tone={(manualRequests ?? []).length ? "warn" : "neutral"}
          href="/app/time"
        />
      </div>

      <div className="grid gap-2 sm:grid-cols-3">
        <KpiCard label={t("kpiClockedIn")} value={kpis.onDuty + kpis.clockedOut} hint={t("kpiClockedInHint")} />
        <KpiCard label={t("kpiEndingSoon")} value={endingSoon} hint={t("kpiEndingSoonHint")} />
        <KpiCard label={t("kpiUpcoming")} value={kpis.upcoming} hint={t("kpiUpcomingHint")} />
      </div>

      <AttendanceBoard
        rows={filtered}
        filters={filters}
        sites={sites ?? []}
        departments={departments ?? []}
      />

      <div className="grid gap-3 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t("openAlerts")}</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-2">
            {(alerts ?? []).length === 0 && (
              <p className="text-sm text-muted-foreground">{t("noAlerts")}</p>
            )}
            {((alerts ?? []) as unknown as Array<{
              id: string;
              type: string;
              minutes_delta: number;
              created_at: string;
              employees: { full_name: string } | null;
            }>).map((a) => (
              <div key={a.id} className="flex items-center justify-between gap-2 text-sm">
                <span>
                  <span className="font-medium">{a.employees?.full_name ?? "—"}</span>{" "}
                  <span className="text-muted-foreground">
                    · {formatMinutes(a.minutes_delta)} · {fmtTime(a.created_at)}
                  </span>
                </span>
                <Badge variant={a.type === "no_show" ? "destructive" : "warning"}>
                  {t(`alert_${a.type}`)}
                </Badge>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t("openShifts")}</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-2">
            {(openShifts ?? []).length === 0 && (
              <p className="text-sm text-muted-foreground">{t("noOpenShifts")}</p>
            )}
            {((openShifts ?? []) as unknown as Array<{
              id: string;
              start_time: string;
              end_time: string;
              required_role: string | null;
              jobs: { client_name: string; locations: { name: string } | null } | null;
            }>).map((s) => (
              <div key={s.id} className="flex items-center justify-between gap-2 text-sm">
                <span>
                  <span className="font-medium">
                    {/* location names localize; a client-name fallback never does */}
                    {s.jobs?.locations?.name ? (
                      <SiteName value={s.jobs.locations.name} />
                    ) : (
                      (s.jobs?.client_name ?? "—")
                    )}
                  </span>{" "}
                  <span className="text-muted-foreground tabular-nums">
                    {fmtTime(s.start_time)}–{fmtTime(s.end_time)}
                  </span>
                </span>
                <span className="text-xs text-muted-foreground">
                  <Term value={s.required_role} />
                </span>
              </div>
            ))}
            <Link href="/app/shifts" className="mt-1 text-xs font-medium text-primary hover:underline">
              {t("allShifts")}
            </Link>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
