-- Clockwise · Migration 0005 · Live Operations (Phase A)
-- Attendance alerting: late, no-show, early clock-out.
-- Alerts are generated by server-side evaluation (idempotent, cron-safe),
-- never by a manager opening the dashboard.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type public.attendance_alert_type as enum
  ('late_clock_in','no_show','early_clock_out');

create type public.attendance_alert_status as enum
  ('open','acknowledged','resolved');

alter type public.notification_type add value if not exists 'late_clock_in';
alter type public.notification_type add value if not exists 'no_show';
alter type public.notification_type add value if not exists 'early_clock_out';

-- ---------------------------------------------------------------------------
-- attendance_alerts
-- One row per (assignment, alert type) — the unique constraint is what makes
-- repeated evaluation runs idempotent: re-running never duplicates an alert.
-- ---------------------------------------------------------------------------
create table public.attendance_alerts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  employee_id uuid not null references public.employees(id) on delete cascade,
  shift_assignment_id uuid not null references public.shift_assignments(id) on delete cascade,
  time_entry_id uuid references public.time_entries(id) on delete set null,
  type public.attendance_alert_type not null,
  minutes_delta integer not null default 0, -- minutes late, or minutes early on clock-out
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  status public.attendance_alert_status not null default 'open',
  acknowledged_by uuid references public.profiles(id) on delete set null,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shift_assignment_id, type)
);

create index on public.attendance_alerts (company_id, status, created_at desc);
create index on public.attendance_alerts (company_id, type, created_at desc);
create index on public.attendance_alerts (employee_id, created_at desc);

create trigger set_updated_at before update on public.attendance_alerts
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Grants + RLS
-- Alerts are operational data: staff read and acknowledge them inside their
-- tenant; employees never read them. Rows are written by the evaluation
-- runner (service role) — no INSERT policy for authenticated users.
-- ---------------------------------------------------------------------------
grant select, insert, update, delete on public.attendance_alerts
to authenticated, service_role;

alter table public.attendance_alerts enable row level security;

create policy attendance_alerts_select on public.attendance_alerts
  for select to authenticated using (app.is_staff(company_id));

create policy attendance_alerts_ack on public.attendance_alerts
  for update to authenticated
  using (app.is_staff(company_id)) with check (app.is_staff(company_id));

-- ---------------------------------------------------------------------------
-- Realtime: the dashboard subscribes to attendance-relevant changes.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    execute 'alter publication supabase_realtime add table public.attendance_alerts';
    execute 'alter publication supabase_realtime add table public.time_entries';
    execute 'alter publication supabase_realtime add table public.shift_assignments';
  end if;
end $$;
